### ISSUE TITLE
Suggestion: Configuration file + mu plugin

### ISSUE THREAD

**Issue by ginsterbusch** [norcross/control-wp-core-emails#2]
Also I'd like to suggest the usage of a configuration file. As [somebody else already implied](https://wptavern.com/disable-specific-wordpress-update-emails-with-the-control-wp-core-emails-plugin#comment-198592), managing multiple WP installs (eg. 20+) could quickly turn into a big fat PITA. Thus adding a configuration file and extending the plugin for MU usage, would greatly improve its value ;)

My suggested scheme as follows:
### 1. Add configuration file

Should be dropped straight into the upload directory, just like this:
https://gist.github.com/ginsterbusch/b4d84eb6256cd9373210efcca2764cdf
### 2. Turn or add the main class as custom MU plugin

You'd just drop both the config file and the MU plugin into the MU directory, and be done. Could easily be automated ;)

cu, w0lf.

**Comment by norcross** [comment]
this is intended for regular users who likely aren't familiar with the whole `mu-plugins` folder concept. while my use case (having 100's of sites), there's still value for folks that have 5 or 10.

as such, anyone who's capable of setting and using a mu-plugin can do so on their own. I don't intend on adding that functionality.
